custom_components/battery_notes/data/library.json

Populated library a bit with different z2m and ble sensors across different integrations + 1 lock

New sensors

---

custom_components/battery_notes/data/library.json

Added Aqara Leak sensor and Aqara mini Switch

Update library.json: Aqara Leak / Aqara Switch

---

custom_components/battery_notes/data/library.json

Added TS0201 Temperature and humidity sensor to the library

Add TS0201 to library.json

---

custom_components/battery_notes/data/library.json

Added IBS-TH by INKBIRD

---

custom_components/battery_notes/data/library.json

Added Tado VA01 Radiator valve (older version of the VA02)

Update library.json - Tado VA01 Radiator Valve

---

custom_components/battery_notes/data/library.json

These are how two of my Aqara Zigbee devices showed up.

Add 2 Devices

---

custom_components/battery_notes/data/library.json

added Orvibo SM11 zigbee Door & Window Sensor
https://zigbee.blakadder.com/Orvibo_SM11.html

Added Orvibo SM11 Door & Window Sensor

---

custom_components/battery_notes/data/library.json

Added Tado SU02 (Wireless Thermostat) and SwitchBot Bot (Called woHand when imported by the SwitchBot Bluetooth integration)

Added Tado SU02 and SwitchBot Bot

---

custom_components/battery_notes/data/library.json

Aqara Opple Switch 2 bands
Aqara Opple Switch 3 bands
Bosch Radiator Thermostat II
Tuya Smart Knob

Add some new devices

---

custom_components/battery_notes/data/library.json

eQ-3: HmIP-WTH-2
a few Zigbee devices with deCONZ: Develco (AQSZB-110), eWeLink (TH01), IKEA (Tradfri ON/OFF, SYMFONISK, RODRET), LUMI/Aqara (Opple switch, temperature, water leak, illuminance, cube, magnet)

Added a few devices

---

custom_components/battery_notes/data/library.json

Add Fibaro FGSD002 Smoke Sensor

Add Fibaro FGSD002 Smoke Sensor

---

custom_components/battery_notes/data/library.json

Adds support for common Aqara and Philips Hue Zigbee & Xiaomi BLE devices

---

custom_components/battery_notes/data/library.json

added battery type for 
HKZW-DWS01 : Door and Window Sensor, from HANK Electronics Ltd

Add HKZW-DWS01 detector

---

custom_components/battery_notes/data/library.json

Added Third Reality, Inc Zigbee devices, 3RDS17BZ - Contact Sensor, 3RSS009Z - Smart Switch, 3RWS18BZ - Water Leak Sensor

Update library.json Added Third Reality devices

---

README.md
custom_components/battery_notes/__init__.py
custom_components/battery_notes/config_flow.py
custom_components/battery_notes/const.py
custom_components/battery_notes/data/library.json
custom_components/battery_notes/diagnostics.py
custom_components/battery_notes/entity.py
custom_components/battery_notes/library_coordinator.py
custom_components/battery_notes/library_updater.py
custom_components/battery_notes/manifest.json
custom_components/battery_notes/sensor.py

Update the library from GitHub approximately every 24 hours

Auto Library Update

---

custom_components/battery_notes/data/library.json

remove duplicate entries for LUMI devices

---

custom_components/battery_notes/data/library.json

Add Ecolink TILT-ZWAVE2.5-ECO tilt sensor

Add Ecolink tilt sensor

---

custom_components/battery_notes/data/library.json

Add more devices:
- IKEA of Sweden / Remote Control N2
- LUMI / lumi.airrtc.agl001
- Xiaomi / LYWSD03MMC/MJWSD05MMC_PVVX
- TZE200_b6wax7g0 / TS0601

Add more devices

---

custom_components/battery_notes/data/library.json
custom_components/battery_notes/translations/de.json

Added German translation
Added Hue tap dial switch (RDM002)
Added Hue dimmer switch (RWL022)

Added German translation, Hue tap dial switch (RDM002), Hue dimmer switch (RWL022)

---

custom_components/battery_notes/data/library.json

* Aeotec ZWA005 - TriSensor (Z-Wave)
* Aeotec ZWA039 - aerQ sensor (Z-Wave)
* Govee H51xx - Temp/Humid. sensor (BT)
* Mopeka Pro Plus - Propane tank monitor (BT)
* TUO Smart Button - (Thread / Matter)

Add multiple devices to DB

---

custom_components/battery_notes/data/library.json

* Correction: Mopeka Pro Plus -> model # M1015
* Add Mopeka Pro Check M1017 - 20 lb propane tank monitor (BT)

Fix Mopeka sensor types

---

custom_components/battery_notes/data/library.json

Added frient A/S HESZB-120 to the library

frient A/S HESZB-120

---

custom_components/battery_notes/data/library.json

This PR adds the following devices:
- eWeLink SNZB-02P Temperature and Humidity Sensor
- frient A/S SMSZB-120 Smoke Alarm
- ZHA model names for[Signify Netherlands B.V. devices

Updates library.json

---

custom_components/battery_notes/data/library.json

Added eQ-3 HM-Sec-SCo window and door contact.

library.json update

---

custom_components/battery_notes/data/library.json

Added iMagic by GreatStar 1116-S
Added CentraLite 3210-L
Added NYCE 3043

updated library.json

---

custom_components/battery_notes/data/library.json

New device: Nedis Door and Windows sensor

---

custom_components/battery_notes/data/library.json

Added to the library:
- Sonoff button (Zigbee via ZHA),
- Xiaomi Mi thermometer2 (LYWSD03MMC) whith custom firmware and BTHome reporting,
- Tuya ZigBee Smart Scene Switch 1-4 Gang (Zigbee via ZHA),

Devices added to the library

---

custom_components/battery_notes/data/library.json

Added S to end of Smartthings and Fixed Model Name to be complete name in HA

Fixed Samsung Leak Sensor Entry

---

custom_components/battery_notes/data/library.json

added two missing August locks to library.json

added two missing August locks to library.json

---

custom_components/battery_notes/translations/pl.json

Added Polish translation

---

custom_components/battery_notes/data/library.json

I added batteries def from my inventory

add missing battery info

---

custom_components/battery_notes/library_updater.py

Perform discovery on library update

Rediscovery

---

custom_components/battery_notes/data/library.json

see https://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/max/bda_portal/BC-TC-C-WM-4_UM_EN.pdf

library.json: Add MAX Wall Thermostat

---

custom_components/battery_notes/data/library.json

see https://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/max/bda_portal/BC-PB-2-WM-2_UM_EN.pdf

library.json: Add MAX Eco Switch

---

custom_components/battery_notes/data/library.json

I had entered two wrong models this pull request will correct it.

Fixed wrong models

---

.github/workflows/json_librarian.yml

as discussed
https://github.com/andrew-codechimp/bn-device-test/pull/71

save pip cache between runs

---

custom_components/battery_notes/binary_sensor.py
custom_components/battery_notes/button.py
custom_components/battery_notes/sensor.py

Handle deleted device

---

custom_components/battery_notes/coordinator.py
custom_components/battery_notes/sensor.py

Fix issue with friendly name overriding

---

custom_components/battery_notes/data/library.json

Added the Honeywell TH6320ZW2007 thermostat.

Add Honeywell TH6320ZW2007

---

custom_components/battery_notes/data/library.json

Added some more devices I have, I hope it it sorted correctly.
```json
{
"manufacturer": "Lidl",
"model": "Silvercrest smart button (HG08164)",
"battery_type": "CR2032"
},
{
"manufacturer": "Trust",
"model": "Smoke detector (ZSDR-850)",
"battery_type": "CR123A"
},
{
"manufacturer": "TuYa",
"model": "Motion sensor (TS0202)",
"battery_type": "CR2450"
},
{
"manufacturer": "TuYa",
"model": "Security remote control (TS0215A_remote)",
"battery_type": "CR2032"
}
```

Add extra devices to library

---

custom_components/battery_notes/data/library.json

Add Blueforcer and Dreame devices

---

custom_components/battery_notes/data/library.json

see https://www.zigbee2mqtt.io/devices/WXKG02LM_rev2.html

support Aqara WXKG02LM_rev2

---

custom_components/battery_notes/data/library.json

https://github.com/eifinger/hass-weenect

support Weenect pet/child trackers

---

custom_components/battery_notes/data/library.json

The manufacturer and model were swapped

Correct Yale YRL256

---

custom_components/battery_notes/data/library.json

Added new device Eaton - Ellipse ECO 650

Device: Eaton - Ellipse ECO 650

---

custom_components/battery_notes/data/library.json

This PR is a follow-up of discussion #1912.

Add Sure Pet Care 'startswith' Feeder (Batery Notes 2.4.0)

---

custom_components/battery_notes/translations/pt.json

Improved the Portuguese translation.
Added some of the missing translations, and revamped others.

PT Translation

---

custom_components/battery_notes/data/library.json

now matches all other 9V batteries

9-volt to 9V

---

custom_components/battery_notes/data/library.json

Fixed 3RDTS01056Z manufacturer name

---

custom_components/battery_notes/data/library.json

Here is the soil sensor I'm using. It has 2 AA batteries. 
https://a.aliexpress.com/_EInyupx

Add soil sensor

---

custom_components/battery_notes/data/library.json

https://a.aliexpress.com/_Ev4WAZj

Add Xiomi E-ink Bluetooth thermometer

---

custom_components/battery_notes/data/library.json

Hi @andrew-codechimp,
I was asked to make upstream changes to Anrijs/Aranet4-Python, wich will result in a change of model names. The new model names are implemented [here](https://github.com/Anrijs/Aranet4-Python/pull/57/files) and correspond to the official names.
Thought I'd make this request before the next release of HA-Battery-Notes
Cheers, Lucas

Update Aranet model names because of upstream changes

---

library/library.json

Added Third Reality 3RTHS24BZ - from Z2M

---

library/library.json

Hi,
I uploaded several devices, but they are still not supported, so I try with this pull request. I hope this is correct since this is the first time I do this kind of modification :)

Reworked json library
