custom_components/battery_notes/data/library.json
These two Zigbee devices both use CR2032 batteries.
The rat trap uses 4 'C' cells.
=> add eWeLink DS01, VictorPest.com Rat Trap, and LUMI lumi.weather

custom_components/battery_notes/data/library.json, schema.json
Excited to see where this project goes!
This is just to make editing the library file a bit easier in editors. Tested in VSCode.
Note that the minimum on battery quantity is exclusive. Using `1` prevents 1 or lower as a value.
=> Link and expand JSON schema for easier editing of library file

custom_components/battery_notes/data/library.json
Added Airthings Wave+
Added Schlage BE469ZP
Added SmartThings Multipurpose sensor (2016 and 2018)
Added Zooz ZSE40, ZSE41 and ZSE42
=> Added Airthings, Schlage, SmartThings and Zooz batteries

custom_components/battery_notes/data/library.json
Updated library to include the following:
* Kwikset HALO-01 smart Door locks (4 x AA)
* Google Topaz-2.7 Nest Protect wired model (3 x AA Energizer Ultimate Lithium “L91”)
* Google KR1 Nest Temperature Sensor (1 x CR2 Lithium)
* rtl_433 Acurite Tower (2 x AA)
=> Updated library.json to include addition of Kwikset HALO-01, Google Topaz-2.7, Google KR1 and Acurite Tower 06002RM

custom_components/battery_notes/data/library.json
iNode Energy Meter, Electra Washbasin Faucet, Shelly Door/Window 2, Shelly Flood, Shelly H&T, Temperature & humidity sensor with display (TS0201), Aqara T1 light intensity sensor (GZCGQ11LM), XMWSDJ04MMC
=> Add devices from iNode, Oras/Hansa, Shelly, Tuya and Aqara/Xiaomi

custom_components/battery_notes/data/library.json
Adds the ecobee [smart temperature sensor](https://www.ecobee.com/en-us/accessories/smart-temperature-occupancy-sensor/#Features-and-Specs) and older [room temperature sensor](https://support.ecobee.com/s/articles/Room-Sensors-FAQs-Setup-Guide-and-Troubleshooting) battery types.
=> Add ecobee room sensor and smart sensor

custom_components/battery_notes/data/library.json
Adds [Sonoff SNZB-01 wireless button](https://sonoff.tech/product/gateway-and-sensors/snzb-01/) battery type.
=> Add Sonoff SNZB-01 button

custom_components/battery_notes/data/library.json
- Aeotec ZWA003 Z-Wave 4-button remote
- Ecolink DWZWAVE25 Z-Wave contact sensor
- SmartThings IM6001-BTP01 Zigbee button
- SmartThings IM6001-MTP01 Zigbee motion sensor
Note that the Aeotec 4-button remote's battery is an LIR2450: it is both a standard type of removable/replaceable battery and a rechargeable battery. I opted to put the battery type instead of noting it as "Rechargeable" since that indicates a bespoke and usually non-removable/replaceable battery.
=> Add devices to library

custom_components/battery_notes/data/library.json
Added "Aqara Door and Window Sensor P2 by Aqara". This is the device info displayed in **Home Assistant  > Settings > Devices & services** when I added it to my instance of HA via the Matter (BETA) integration. This is my first ever pull request, so please forgive me if I did anything incorrectly. Thank you!
=> Add Aqara Door and Window Sensor P2

custom_components/battery_notes/data/library.json
- Xiaomi Aqara Smart Radiator Thermostat E1 (SRTS-A01)
- Alias: Xiaomi SRTS-A01
- SONOFF Zigbee thermostatic radiator valve (TRVZB)
- Alias: SONOFF TRVZB
=> Added device details (Xiaomi SRTS-A01, Sonoff TRVZB)

custom_components/battery_notes/data/library.json
https://www.aliexpress.us/item/3256805753051657.html
These Tuya sensors (or clones more likely) with randomly-generated manufacturer data are annoying. I sure hope they're at least consistent for the same product.
=> add Tuya door sensor TS0203 by _TZ3000_yxqnffam

README.md, custom_components/battery_notes/__init__.py, custom_components/battery_notes/config_flow.py, custom_components/battery_notes/const.py
Filter devices when manually adding to just those with batteries
=> Filterdevices

custom_components/battery_notes/data/library.json
- Hue motion sensor (SML003) from Philips (via Hue bridge and ZHA)
- Door/window sensors from Fibaro (via Z-Wave)
- Motion and Door/window sensors from Aeotec/AEON (via Z-Wave)
- TRVs from Eurotronics (Spirit) and Danfoss (via Z-Wave)
- Smart Anemometer and Rain Gauge from Netatmo
- Additional manufacturer/model combination for the Hue dimmer switch RWL021
=> Additional devices

custom_components/battery_notes/data/library.json
Added CentraLite Motion and Door sensors
Added  BRK Brands, Inc. and FirstAlert ZCOMBO
Added IKEA of Sweden TREDANSEN block-out cellul blind roller blind 
Added HAB Home Intelligence LLC iblinds V3 roller blinds retrofit kit
Added Quikset door locks
=> Added CentraLite, FirstAlert, IKEA and HAB Devices

custom_components/battery_notes/data/library.json
Fix battery type for Zooz ZEN34, from AAA to CR2032
=> Corrected battery type for Zooz ZEN34

custom_components/battery_notes/data/library.json
I removed the CentraLite device that I had added by mistake, this device has no battery
=> removed CentraLite 3210-L as it has no battery, it was added by mistake

custom_components/battery_notes/data/library.json
The Netatmo "Smart Indoor Module" had the battery quantity set to 2 when it should be 4 (https://www.netatmo.com/additional-smart-indoor-module/specifications), I think it's the same physical device (or a newer version) as the "Additional Indoor Module" that's defined a few lines above this one.
=> Update Netatmo Smart Indoor Module battery quantity from 2 to 4

custom_components/battery_notes/data/library.json
My Xiaomi nightlights are not detected because they advertise themselves as MJYD02YL (instead of MJYD02YL-A). They look exactly like the MJYD02YL-A ones, maybe it's a different revision.
=> library.json: Add Xiaomi MJYD02YL

custom_components/battery_notes/data/library.json
MAX! Window Sensors take 2 AAA batteries (not AA), see https://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/max/bda_portal/BC-SC-Rd-WM-2_UM_EN.pdf
=> library.json: Fix MAX! Window Sensor

custom_components/battery_notes/data/library.json
In Home Assistant, they show up as "MUE4094RT", not as "ble MUE4094RT". However, in library.json, all Xiaomi ble night lights are prefixed by "ble". Is that necessary for Battery Notes to work or some sort of artifact?
=> library.json: add Xiaomi MUE4094RT

custom_components/battery_notes/data/library.json
MJYD02YL-A uses AA type of batteries (not AAA)
=> library.json: fix MJYD02YL-A

custom_components/battery_notes/data/library.json, library.md
Looks like #55 listed the Airthings Wave Plus and Allegion BE469ZP as using AAA batteries when they really use AAs. (The quantities were right, though!)
For the Airthings, see the "Additional specifications" section [on this page](https://www.airthings.com/en/wave-plus).
For the Allegion/Schlage, see the "Specifications" section [on this page](https://www.schlage.com/en/home/products/BE469ZPCAMFFF.html).
Thanks for this project! Excited to start using it.
=> Change Airthings Wave Plus and Allegion BE469ZP to AA, not AAA

custom_components/battery_notes/data/library.json, library.md
A handful of library entries with rechargeable batteries used the spelling `Rechargable` instead of the spelling recommended in the project's README.
Unsure if the author(s) want to standardize or leave these as-is for compatibility with existing installs, but figured it was easy enough to send along a PR all the same.
=> Update non-standard spellings of "Rechargeable".

custom_components/battery_notes/data/library.json
This PR adds some LUMI/Aquara devices I have at home that are managed by ZHA but not discovered automagically by Battery-Notes
=> chore: Add missing LUMI devices

custom_components/battery_notes/data/library.json
Add various Aqara sensors (Z2M variant), Sengled door sensors, Airthings Wave Radon, Govee H5074 temp sensors, BlueMaestro Tempo discs. 9 new devices added.
=> Add Aqara, Sengled, Airthings, Govee, BlueMaestro devices to library

custom_components/battery_notes/data/library.json
I wrongly reported the battery types of these in #616 and #618, which this fixes.
=> Update devices: TS0041 by _TZ3000_4upl1fcj + TS0042 by _TZ3000_dfgbtub0

custom_components/battery_notes/data/library.json
Sanity checked myself and Philips 324131092621 was indeed using CR2450 all along, sorry for that change in #1068. Only Philips 929002398602 needed correction from CR2450 to CR2032
=> fix: revert philips 324131092621 battery to CR2450

custom_components/battery_notes/data/library.json, library.md
My SRT321 do not appear under 'Secure Meters' manufacturer anymore,  but 'Secure Meters (UK) Ltd.' I do not know if you want to keep both, neither why this has changed in home assistant or zwave2mqtt. Probably an update in the later.
=> fix: SRT321 changed manufacturer

.github/workflows/json_validate.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .ruff.toml, requirements.txt
* JSON validation was being run when other actions were modified, no longer does
* Added python 3.12 to linting version matrix to watch for use of deprecated syntax and methods
* Remove branch filter from linting workflow (so it lints any forks and PRs)
* Use ruff command line flags to export results as SARIF file and upload to GitHub CodeQL
* Requirements.txt uses ">=X, <X" syntx to allow future minor+patch updates but not future major versions (except to homeassistant)
* Use [uv](https://github.com/astral-sh/uv) for installing requirements in linting action to reduce runtime
=> GH Linting Improvements

custom_components/battery_notes/sensor.py
Background in https://github.com/home-assistant/core/pull/113798
=> Adapt to changes in HA Core PR 113798

docs/services.md
The `battery_notes.check_battery_last_reported` service had parameter `data.days`. This was incorrect and should have been `data.days_last_reported`. The service call is correct in all the community examples.
=> Fixed Incorrectly Named Service Parameter

custom_components/battery_notes/data/library.json
Support for this sensor has already been added, but TuyaBLE integration sets the model name differently, so it requires separate entry for such cases. This should close #1861
=> Plant Sensor SGS01 via TuyaBLE integration

custom_components/battery_notes/data/library.json
* Thermostat radiator valve (TV01-ZB)
* Thermostat radiator valve (ZTRV-ZX-TV01-MS)
Apart from the model name they are identical to the already existing radiator valve. Tested and working on my local HA instance.
Thanks for the awesome component :)
=> Add Moes thermostat radiator valve variants

custom_components/battery_notes/data/library.json
The additional quotes are unnecessary here, and were breaking some templates I was creating with HA 😁 
Also, some IKEA batteries were incorrect and should have been "Rechargeable" (but not with extra quotes).
=> Fix Ring batteries having additional quotes

custom_components/battery_notes/__init__.py, custom_components/battery_notes/data/library.json, custom_components/battery_notes/device.py, custom_components/battery_notes/services.py, library.md
Code tidying to split the service from init
=> Service split

custom_components/battery_notes/data/library.json
Hey, 
it seems that my vallhorn wasn't correctly picked up because of slight differences in the name
=> chore: add alias for Ikea vallhorn

custom_components/battery_notes/data/library.json
Water leak sensor is already there but it was not recognized for me. Mine is added through Homekit and the model is shown as just AS010
=> Add Aqara water leak sensor

custom_components/battery_notes/__init__.py, custom_components/battery_notes/const.py, custom_components/battery_notes/library_updater.py
Internal changes for support of alternative library url
=> Custom library url

custom_components/battery_notes/data/library.json
Added missing device Room thermostat II (RBSH-RTH0-BAT-ZB-EU) from Bosch
=> Added Device: Bosch room thermostat II

docs/community.md, docs/events.md
Updated the community examples to use the new YAML syntax for automations, implemented in HA 2024.10
https://www.home-assistant.io/blog/2024/10/02/release-202410/#improved-yaml-syntax-for-automations
=> Update community.md to use new yaml syntax for automations

docs/blueprints/battery_notes_battery_not_reported.yaml, docs/blueprints/battery_notes_battery_replaced.yaml, docs/blueprints/battery_notes_battery_threshold.yaml
=> Update blueprints to use new yaml syntax for automations

custom_components/battery_notes/data/library.json
Homematic / Homematic IP devices must provide their model name as model and not model-id
=> Update library.json - corrected 3 Homematic entries

custom_components/battery_notes/data/library.json
Battery type was incorrectly configured as "CR2439"
=> Fix VCZ1 battery type

library/library.json
Reverts andrew-codechimp/HA-Battery-Notes#3369
My bad, already existed and this introduced a typo in the battery model.
=> Revert "Device: _TZE200_3towulqd - TS0601"

custom_components/battery_notes/translations/de.json
This fixes a missmatch in the German description for a repair issue.
=> fix: naming issue in German repair issue description
